/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calculadora_1(char *host,int entero1, char operador, int entero2)
{
	CLIENT *clnt;
	int  *result;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, PRIMERA, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	if (operador == '+'){
		result = sumar_1(entero1, entero2, clnt);
	} else if (operador == '-'){
			result = restar_1(entero1, entero2, clnt);
	} else if (operador == 'x') {
		result = multiplicar_1(entero1, entero2, clnt);
	} else if (operador == '/') {
		result = dividir_1(entero1, entero2, clnt);
	}

	if (result == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("Resultado de %i %c %i: %i\n",entero1,operador,entero2,*result);
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int entero1;
	char operador;
	int entero2;

	if (argc < 5) {
		printf ("usage: <server_host> <un_entero> <operador> <otro_entero>\n");
		exit (1);
	}

	host = argv[1];
	entero1 = atoi(argv[2]);
	operador = argv[3][0];
	entero2 = atoi(argv[4]);	

	calculadora_1 (host, entero1, operador, entero2);
exit (0);
}
