/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DNS2_H_RPCGEN
#define _DNS2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct anadirdominio_1_argument {
	char *arg1;
	char *arg2;
};
typedef struct anadirdominio_1_argument anadirdominio_1_argument;

#define DNS2 0x20000156
#define PRIMERA 1

#if defined(__STDC__) || defined(__cplusplus)
#define COMPROBAR 1
extern  char ** comprobar_1(char *, CLIENT *);
extern  char ** comprobar_1_svc(char *, struct svc_req *);
#define ANADIRDOMINIO 2
extern  int * anadirdominio_1(char *, char *, CLIENT *);
extern  int * anadirdominio_1_svc(char *, char *, struct svc_req *);
#define BORRARDOMINIO 3
extern  int * borrardominio_1(char *, CLIENT *);
extern  int * borrardominio_1_svc(char *, struct svc_req *);
extern int dns2_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define COMPROBAR 1
extern  char ** comprobar_1();
extern  char ** comprobar_1_svc();
#define ANADIRDOMINIO 2
extern  int * anadirdominio_1();
extern  int * anadirdominio_1_svc();
#define BORRARDOMINIO 3
extern  int * borrardominio_1();
extern  int * borrardominio_1_svc();
extern int dns2_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_anadirdominio_1_argument (XDR *, anadirdominio_1_argument*);

#else /* K&R C */
extern bool_t xdr_anadirdominio_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DNS2_H_RPCGEN */
