/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dns2.h"
#include <stdbool.h>

char * tablaNombre[100];
char * tablaIP[100];
int tam_array = 0;

char **
comprobar_1_svc(char *arg1,  struct svc_req *rqstp)
{
	static char * result;

	char * valor;
	bool salir = false;
	char * valorIP;

	for (int i=0; i<tam_array && !salir; i++){
		valor = tablaNombre[i];
		valorIP = tablaIP[i];

		if (!strcmp(valor, arg1)){
			salir = true;
		}
	}

	if (salir){
		result = valorIP;
	} else {
		result = "No encontrado";
	}

	return &result;
}

int *
anadirdominio_1_svc(char *arg1, char *arg2,  struct svc_req *rqstp)
{
	static int  result;

	if (tam_array <= 100){
		int longitud_arg = strlen(arg1) + 1;
		tablaNombre[tam_array] = (char*)malloc(longitud_arg * sizeof(char));
		strcpy(tablaNombre[tam_array], arg1);

		longitud_arg = strlen(arg2) + 1;
		tablaIP[tam_array] = (char*)malloc(longitud_arg * sizeof(char));
		strcpy(tablaIP[tam_array], arg2);

		tam_array++;
		result = 0;
	} else {
		result = 1;
	}

	return &result;
}

int *
borrardominio_1_svc(char *arg1,  struct svc_req *rqstp)
{
	static int  result;

	char * valor;
	int indiceBorrar = 101;
	bool salir = false;

	for (int i=0; i<tam_array && !salir; i++){
		valor = tablaNombre[i];

		if (!strcmp(valor, arg1)){
			indiceBorrar = i;
			salir = true;
		}
	}

	if (indiceBorrar != 101){
		char * arrayCopiaNombre[100];
		char * arrayCopiaIP[100];
		int indice = 0;
		result = 0;

		for (int i=0; i<tam_array; i++){
			if (i != indiceBorrar){
				arrayCopiaNombre[indice] = tablaNombre[i];
				arrayCopiaIP[indice] = tablaIP[i];
				indice++;
			}
		}

		//tablaNombre = arrayCopia; 
		tam_array--;
		for (int i=0; i<tam_array; i++){
			tablaNombre[i] = arrayCopiaNombre[i];
			tablaIP[i] = arrayCopiaIP[i];
		}
	} else {
		result = 1;
	}

	return &result;
}
